Admin_Capstone_KPS/Controllers/EmployeeController.cs
using HmsService.Models.Entities;
using HmsService.Sdk;
using HmsService.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebAdmin.Controllers
{
    public class EmployeeController : Controller
    {
        HmsEntities entities = new HmsEntities();
        // GET: Employee
        public ActionResult Index()
        {
            return View("Editor");
        }

        public ActionResult Create(EmployeeViewModel emp) {
            try
            {
                EmployeeApi employeeApi = new EmployeeApi();
               employeeApi.Create(emp);
            }
            catch (Exception e) {
            }
            return View("Index");
        }
    }
}

Admin_Capstone_KPS/Views/Employee/Editor.cshtml
@using HmsService.ViewModels;
@model EmployeeViewModel
@{
    ViewBag.Title = "Editor";
}

@using (Html.BeginForm("Create", "Employee"))
{
    <div class="card">
        <div class="card-header">
            <strong>Credit Card</strong>
            <small>Form</small>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-sm-12">
                    <div class="form-group">
                        @Html.LabelFor(emp=> emp.EmployeeName)
                        @Html.TextBoxFor(emp=>emp.EmployeeName, new { @class= "form-control" })
                    </div>
                </div>
            </div>
            <!--/.row-->
            <div class="row">
                <div class="col-sm-12">
                    <div class="form-group">
                        <label for="ccnumber">Credit Card Number</label>
                        <input type="text" class="form-control" id="ccnumber" placeholder="0000 0000 0000 0000">
                    </div>
                </div>
            </div>
            <!--/.row-->
            <div class="row">
                <div class="form-group col-sm-4">
                    <label for="ccmonth">Month</label>
                    <select class="form-control" id="ccmonth">
                        <option>1</option>
                        <option>2</option>
                        <option>3</option>
                        <option>4</option>
                        <option>5</option>
                        <option>6</option>
                        <option>7</option>
                        <option>8</option>
                        <option>9</option>
                        <option>10</option>
                        <option>11</option>
                        <option>12</option>
                    </select>
                </div>
                <div class="form-group col-sm-4">
                    <label for="ccyear">Year</label>
                    <select class="form-control" id="ccyear">
                        <option>2014</option>
                        <option>2015</option>
                        <option>2016</option>
                        <option>2017</option>
                        <option>2018</option>
                        <option>2019</option>
                        <option>2020</option>
                        <option>2021</option>
                        <option>2022</option>
                        <option>2023</option>
                        <option>2024</option>
                        <option>2025</option>
                    </select>
                </div>
                <div class="col-sm-4">
                    <div class="form-group">
                        <label for="cvv">CVV/CVC</label>
                        <input type="text" class="form-control" id="cvv" placeholder="123">
                    </div>
                </div>
            </div>
            <!--/.row-->
        </div>
    </div>
    <button type="submit">Submit</button>
}

Admin_Capstone_KPS/Views/Employee/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<table id="UserDatatable" class="table table-striped table-bordered table-hover table-condensed">
    <thead>
        <tr>
            <th>
                <label class="">STT</label>
            </th>
            <th>
                <label class="">Tên</label>
            </th>
            <th>
                <label class="">Ngày sinh</label>
            </th>
            <th>
                <label class="">Địa chỉ</label>
            </th>
        </tr>
    </thead>
    <tbody></tbody>
</table>
<script>
    $(document).ready(function () {
        InitUserDatatable();
    });

    function InitUserDatatable() {

            $("#UserDatatable").dataTable({

                "bSort": false,
                "bServerSide": true,
                "bRetrieve": true,
                "bScrollCollapse": true,
                "sAjaxSource": "@Url.Action("IndexList", "Employee")",
                "bProcessing": true,
                "aLengthMenu": [10, 25, 50],
                "bFilter": true,
                "oLanguage": {
                    "sSearchPlaceholder": "Tên sản phẩm",
                    "sSearch": "Tìm kiếm:",
                    "sZeroRecords": "Không có dữ liệu phù hợp",
                    "sInfo": "Hiển thị từ _START_ đến _END_ trên tổng số _TOTAL_ dòng",
                    "sEmptyTable": "Không có dữ liệu",
                    "sInfoFiltered": " - lọc ra từ _MAX_ dòng",
                    "sLengthMenu": "Hiển thị _MENU_ dòng",
                    "sProcessing": "Đang xử lý...",
                    "oPaginate": {
                        "sNext": "<i class='fa fa-chevron-right'></i>",
                        "sPrevious": "<i class='fa fa-chevron-left'></i>"
                    }
                },
                "aoColumnDefs": [
                    {
                        "aTargets": [0, 1, 2, 3],
                        "bSortable": false,
                        "sClass": "text-center mid-v-align"
                    }, {
                        "bSortable": false,
                        "sClass": "text-center"
                    },

                ],
                "bAutoWidth": false,
            }).fnSetFilteringDelay(delaySearch);;
        }
</script>